version: '3'
 
services:
  dbnba:
    image: mysql:5.7
    container_name: dbnba
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: appnba_db
      MYSQL_USER: rootroot
      MYSQL_PASSWORD: rootroot
    ports:
      - "6034:3306"
    volumes:
      - dbdata:/var/lib/mysql6
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pmanba
    links:
      - dbnba
    environment:
      PMA_HOST: dbnba
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80
volumes:
  dbdata:
